"""deleted field favourites in model Favourites

Revision ID: 0a1c7d39ea3f
Revises: ecc38434f1e5
Create Date: 2024-03-13 19:13:06.921763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1c7d39ea3f'
down_revision: Union[str, None] = 'ecc38434f1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourites', 'favourites')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites', sa.Column('favourites', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
