"""Added voted field for models Vote

Revision ID: 879b41581147
Revises: ed12b34e6393
Create Date: 2024-02-28 18:58:25.287253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879b41581147'
down_revision: Union[str, None] = 'ed12b34e6393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('voted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'voted')
    # ### end Alembic commands ###
